{% set name = "graphdatascience" %}
{% set version = "1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/graphdatascience-{{ version }}.tar.gz
  sha256: ba8166632b12307140f6fbef2dcafd862fa7e0383babb89a27b0239af84c8ba8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.9
    - multimethod >=1.0,<2.0
    - neo4j-python-driver >=4.4.12,<6.0
    - pandas >=1.0,<3.0
    - pyarrow >=15.0.2, < 19.0
    - textdistance >=4.0,<5.0
    - tqdm >=4.0,<5.0
    - typing-extensions >=4.0,<5.0
    - requests
    - tenacity >= 9.0

test:
  imports:
    - graphdatascience
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: graphdatascience

  - name: graphdatascience.ogb
    requirements:
      host:
        - python
      run:
        - python
        - ogb >=1.0,<2.0
        - {{ pin_subpackage('graphdatascience', exact=True) }}
      test:
        imports:
          - graphdatascience.ogb

  - name: graphdatascience.networkx
    requirements:
      host:
        - python
      run:
        - python
        - networkx >=2.0,<4.0
        - {{ pin_subpackage('graphdatascience', exact=True) }}
      test:
        imports:
          - graphdatascience.networkx

about:
  home: https://neo4j.com/product/graph-data-science/
  summary: A Python client for the Neo4j Graph Data Science (GDS) library
  dev_url: https://github.com/neo4j/graph-data-science-client
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - mbestipa
